Repository Ayush7614/CheatSheet-Templates, pull requests merged in 2021-10, with the labels that each got.

#11 mongoDB_cheatsheet_added
  MongoDB Cheatsheet/index.html
  MongoDB Cheatsheet/prism.css
  MongoDB Cheatsheet/prism.js
  MongoDB Cheatsheet/style.css
Labels: hacktoberfest 21, hacktoberfest-accepted, Open source

#12 Update style.css
  JavaScript Cheatsheet/style.css
Labels: hacktoberfest 21, hacktoberfest-accepted, Open source

#13 Update style.css
  GitHub Cheatesheet/style.css
Labels: hacktoberfest 21, hacktoberfest-accepted, Open source

#14 Update style.css
  Python Cheatsheet/style.css
Labels: hacktoberfest 21, hacktoberfest-accepted, Open source

#10 Changes made.
  GitHub Cheatesheet/index.html
Labels: hacktoberfest 21, hacktoberfest-accepted, Open source

#15 Update style.css
  HTML Cheatsheet/style.css
  Python Cheatsheet/style.css
Labels: hacktoberfest 21, hacktoberfest-accepted, Open source

#19 Update style.css
  Python Cheatsheet/style.css
Labels: hacktoberfest 21, hacktoberfest-accepted, Open source

#16 #8
  index.html
  style.css
Labels: hacktoberfest 21, hacktoberfest-accepted, Open source

#24 Update html and css file
  MongoDB Cheatsheet/index.html
  MongoDB Cheatsheet/style.css
Labels: hacktoberfest 21, hacktoberfest-accepted, Open source

#25 CSS Cheatsheet
  CSS Cheatsheet/index.html
  Django Cheatsheet
Labels: hacktoberfest 21, hacktoberfest-accepted, Open source

#27 #17 Design a favicon
  GitHub Cheatesheet/index.html
  HTML Cheatsheet/index.html
  JavaScript Cheatsheet/index.html
  Pictures/Awesome Cheatsheets.png
  Python Cheatsheet/index.html
  index.html
Labels: hacktoberfest 21, hacktoberfest-accepted, Open source

#32 PHP cheatsheet added
  PHP Cheatsheet/index.html
  PHP Cheatsheet/prism.css
  PHP Cheatsheet/prism.js
  PHP Cheatsheet/style.css
Labels: hacktoberfest2021, hacktoberfest-accepted, Open source

#33 #28 Java cheatsheet added
  Java Cheatsheet/index.html
  Java Cheatsheet/prism.css
  Java Cheatsheet/prism.js
  Java Cheatsheet/style.css
  Python Cheatsheet/index.html
  index.html
Labels: accepted, hacktoberfest2021, hacktoberfest-accepted, Open source

#37 Update index.html
  JavaScript Cheatsheet/index.html
Labels: accepted, hacktoberfest2021, hacktoberfest-accepted

#38 c++ cheatsheet added
  C++ Cheatsheet/index.html
  C++ Cheatsheet/prism.css
  C++ Cheatsheet/prism.js
  C++ Cheatsheet/style.css
Labels: accepted, hacktoberfest2021, hacktoberfest-accepted, Open source

#73 some css changes
  CSS Cheatsheet/index.html
Labels: hacktoberfest2021, hacktoberfest-accepted

#74 styling
  GitHub Cheatesheet/style.css
Labels: hacktoberfest2021, hacktoberfest-accepted

#75 changes
  Kotlin Cheatsheet/.vscode/settings.json
  Kotlin Cheatsheet/index.html
  Kotlin Cheatsheet/style.css
Labels: hacktoberfest2021, hacktoberfest-accepted
